language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devops4linx
  api:
    key:
      secure: H7EVvJ6s3BLOoLQ4dV6XQPTrbBaixnqDecdXU00nuWZH4JdeOqaoPsh3/wcelwYl3Z7SACdfUrT3DGmT8jmN+bv0J455agt4r+kkJL99l1ea0W4Swl2QV9xkeMQASZguHsv3e9Cixw6q3YFndV6OOi/bLV1qRUUIpYGNiB9DrqulwQhEnLmQwlRBefszFE3KqtWLhCo47pNCLU2jPdAIqUJOeKduS7KCLHPad2KGRIBQ3SGjchnSc4WtoKJzjM9KU09o1O48u44Y9IX7CgJiI+3wY+HzxpCtwsqeDJJJv2rrE9bqiNs01pz8ghUru52TbEiWKnCSMiqx/xlcqI0vPYlbyQQB+NhhMg7YnEpac/aY10sppK58xQiOEj8MZ0d6ZjhIivXNXdChspy65KdHW1mkdN1ckaIOzA9QvdaqS63HYCsdcwNKMdxI5bJnTQmT9H9ZJB+nxuMqZsWBX5uMIPQ1PSdur5t/X1WrjwDZBl1i/ZeIxZiXkmJcOAhv69Xvdc+zEk1oMoliKaboyRN72WWx4FBofPf4X7s+v+Ugr66MDz1MH+mIt21lbpX13YBUv52HbuoHQtaLOIMO6ZmHe5uMM4FaqJvnjyh0nLEXkEA7p5hAcbLw4hrfdKc42r3pv5Hesm3Si7Sk1YfWIel7xpdN8TbK6uIAgHTdMtcFLAw=
