language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devops4linx
  api:
    key:
      secure: AdAR+TMozFye0z8H9E/enTbOQAG/1nQbrjN512zpt9NcZKp2E6/sZEivydPXlGHMN/fKpKEUce08Me77zml7TG535TtYnlVuRftRZxM1dslHPpuxkDfjFk4JdKbNv7Ew21quUfeCijF7KDDKkjvsYsnMtS9QvQXCreQcnsgDxvCCkQHvC6t2jvnd5/F5JfQMG0NMAHIu3sejcm+cQ7phZE0Ge/S++9AuvGLSkapKshE3RW5eC6EsprVOyp3hWevy25FSk2pb9dvMPCoHLSuAiC6t5FUOHjQrB/ZwW+350V/oMOytWYyONc4jq58IuoGnYu/xnqXoeOCTFP4/3yyVk6D/lyGLB+Jn+E7+CXSgbVssKur24hucOIH/Gj6O6MUAq1iJc1YCMumM3T+kQdozsr5VZEQ2rM/Y0G2qcZKw94/zdv4jiV7j9f+RfVfSgzafDKyy03PUelv2qrWrznS/pK+L6aLMBERy6SB9+p4YpX6GtUiy2ybAbFQ5jEklWirRqDbSreG392jQN+gIZ3lBtzZXpck6CYHvdbXJDYXrJfEi8buw8a/CwPOX4zfrHpXwR1uBCcdQwjjpIFR2TIOqWOmP4JkOScuDoofST3fy5A2wDxL0MgWT0O+C0+A+45SEOEfiTx7IMqUTdQKnVe4GnHcMkNwFU194sNXI9NdVO8g=
